# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Carlos's Escience Blog
tagline:          Big Data Econometrics
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Carlos Manzanares
  url:            
  email:          carlos.a.manzanares@vanderbilt.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
